services:
  app:
    image: idgen
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`idgen.sierra.web.id`)
      - traefik.http.services.app.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
